server:
  # 应用端口
  port: 9301

spring:
  application:
    # 应用名称
    name: solo-codegen
  profiles:
    # 环境配置
    active: @profiles.active@
  messages:
    encoding: UTF-8
  # Nacos 参数配置
  cloud:
    nacos:
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置中心文件后缀
        file-extension: yaml
      discovery:
        # 服务发现地址
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:${spring.application.name}-@profiles.active@.yml

  datasource:
    url: jdbc:mysql://localhost:3306/solo-codegen
    username: root
    password: 123456
  # redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-flex:
  global-config:
    # 逻辑删除数据存在标记值,默认值为 0
    normal-value-of-logic-delete: 0
    # 逻辑删除数据删除标记值,默认值为 1
    deleted-value-of-logic-delete: 1

codegen:
  # 生成代码的默认作者
  author: 十一
  # 生成代码的尾巴注释
  tail: 人生若只如初见，何事秋风悲画扇

dubbo:
  application:
    # 关闭qos端口避免单机多生产者端口冲突 如需使用自行开启
    qos-enable: false
  protocol:
    # 使用 dubbo 协议通信
    name: dubbo
    # dubbo 协议端口(-1表示自增端口,从20880开始)
    port: -1
    # 指定dubbo协议注册ip
    # host: 192.168.0.100
  # 消费者相关配置
  consumer:
    # 超时时间
    timeout: 3000
  scan:
    # 接口实现类扫描
    base-packages: org.solo.**.dubbo
  # 自定义配置
  custom:
    # 全局请求log
    request-log: true
    # info 基础信息 param 参数信息 full 全部
    log-level: info

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.solo.codegen.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn