server:
  # 应用端口
  port: 9001

spring:
  application:
    # 应用名称
    name: solo-system
  profiles:
    # 环境配置
    active: @profiles.active@
  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  # Nacos 参数配置
  cloud:
    nacos:
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置中心文件后缀
        file-extension: yaml
      discovery:
        # 服务发现地址
        server-addr: 127.0.0.1:8848
  config:
    import:
      #        - optional:nacos:application-@profiles.active@.yml
      - optional:nacos:${spring.application.name}-@profiles.active@.yml

  datasource:
    url: jdbc:mysql://localhost:3306/solo
    username: root
    password: 123456

  # redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456

mybatis-flex:
  global-config:
    # 逻辑删除数据存在标记值,默认值为 0
    normal-value-of-logic-delete: 0
    # 逻辑删除数据删除标记值,默认值为 1
    deleted-value-of-logic-delete: 1

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # 开启内网服务调用鉴权(不允许越过gateway访问内网服务 保障服务安全)
  check-same-token: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false


dubbo:
  application:
    # 关闭qos端口避免单机多生产者端口冲突 如需使用自行开启
    qos-enable: false
  protocol:
    # 如需使用 Triple 3.0 新协议 可查看官方文档
    # 使用 dubbo 协议通信
    name: dubbo
    # dubbo 协议端口(-1表示自增端口,从20880开始)
    port: -1
    # 指定dubbo协议注册ip
    # host: 192.168.0.100
  # 消费者相关配置
  consumer:
    # 超时时间
    timeout: 3000
  scan:
    # 接口实现类扫描
    base-packages: org.solo.**.dubbo
  # 自定义配置
  custom:
    # 全局请求log
    request-log: true
    # info 基础信息 param 参数信息 full 全部
    log-level: info